spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: secret

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: secret
    baseline-on-migrate: true
