spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: secret

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: my_db

  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: secret
    baseline-on-migrate: true
