server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: secret
#    driverClassName: org.h2.Driver

  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: secret
    schemas: public
    baseline-on-migrate: true



  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create


    show-sql: true

#  database-platform=org:
#    hibernate:
#      dialect:
#        H2Dialect:
#
#  h2:
#    console:
#      enabled: true
#      path: /h2